{% set name = "des-pizza-cutter-metadetect" %}
{% set version = "0.9.1" %}

{% set piff = piff or 'cf' %}

{% set build = 3 %}
{% if piff == 'cf' %}
# prioritize piff package
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-metadetect/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6e48794685092bb65d5191f3a48c27ca5f22daec13d92aa743b7e04ccad5d2a8

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win or py >= 312]
  number: {{ build }}
  string: "{{ piff }}_h{{ PKG_HASH }}_{{ build }}"
  # weigh down eastlake version with track features
  track_features:                                # [piff == "eastlake"]
    - des_pizza_cutter_metadetect_piff_eastlake  # [piff == "eastlake"]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - healpy
    - des-easyaccess
    - des-desmeds
    - meds >=0.9.16
    - ngmix >=2.3.0
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff  # [piff == "cf"]
    - cfitsio
    - metadetect >=0.11.0,<0.12.0a0
    - des-pizza-cutter >=0.7.1
    - des-sxdes >=0.3.0
    - importlib_metadata
    - healsparse >=1.3.0
  # use run constrained to avoid a circular dependency
  run_constrained:        # [piff == "eastlake"]
    - des-eastlake >=0.9  # [piff == "eastlake"]

test:
  imports:
    - pizza_cutter_metadetect
  commands:
    - run-metadetect-on-slices --help
    - python -c "import pizza_cutter_metadetect; assert pizza_cutter_metadetect.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter-metadetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: code to run metadetect on pizza cutter MEDs files

extra:
  recipe-maintainers:
    - beckermr
