{% set name = "des-pizza-cutter-metadetect" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-metadetect/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4001791b4db295ad69b45a65f970d9b3c4f66610e856abb644759faf10b4c72b

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm !=6.3.1
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - healpy
    - des-easyaccess
    - des-desmeds
    - meds >=0.9.14
    - ngmix >=2.3.0
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect >=0.10.0,<0.11.0a0
    - des-pizza-cutter >=0.7.1
    - des-sxdes >=0.3.0
    - importlib_metadata
    - healsparse >=1.3.0

test:
  imports:
    - pizza_cutter_metadetect
  commands:
    - run-metadetect-on-slices --help
    - python -c "import pizza_cutter_metadetect; assert pizza_cutter_metadetect.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter-metadetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: code to run metadetect on pizza cutter MEDs files

extra:
  recipe-maintainers:
    - beckermr
