{% set name = "des-pizza-cutter-metadetect" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-metadetect/archive/refs/tags/{{ version }}.tar.gz
  sha256: b6128af12bfb1b6277f69399cbc14a5cb113e9f4514dd9676539a49ab1d25487

build:
  # this recipe is not noarch due to using the scripts kwarg w/ setuptools
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm !=6.3.1
    - setuptools_scm_git_archive
  run:
    - python
    - numpy
    - scipy
    - galsim
    - fitsio
    - pyyaml
    - numba
    - healpy
    - des-easyaccess
    - des-desmeds
    - meds >=0.9.14
    - ngmix >=2.1.0
    - click
    - esutil
    - sep
    - joblib
    - jinja2
    - tqdm
    - piff
    - cfitsio
    - metadetect >=0.9.0,<0.10.0a0
    - des-pizza-cutter >=0.5.3
    - des-sxdes
    - importlib_metadata
    - healsparse >=1.3.0

test:
  imports:
    - pizza_cutter_metadetect
  commands:
    - run-metadetect-on-slices --help
    - python -c "import pizza_cutter_metadetect; assert pizza_cutter_metadetect.__version__ == '{{ version }}'"

about:
  home: https://github.com/beckermr/pizza-cutter-metadetect
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: code to run metadetect on pizza cutter MEDs files

extra:
  recipe-maintainers:
    - beckermr
